### ISSUE TITLE
Possible pivot

### ISSUE THREAD

**Issue by constsync** [constsync/lyric-reader#17]
What do you guys think about pivoting to making this a progressive web app that reads back to you the definition of a word that the user searches for? I think that would be a bit more useful than having lyrics read? We won't have to change much of our code, we'll just have to point our node proxy service at a different API; and since we don't have that much of the UI built out yet it shouldn't be too much of a pain to pivot. Any opinions on this? @konqa @constbot @rowanD72

**Comment by constsync** [comment]
Gonna move this project over to React and make the whole purpose of the codebase to be a progressive web app that allows a user to search for a word and get back a definition of that word, an example of it being used and function that reads the word searched for. I feel like this would be a bit more useful than making this read song lyrics.

**Comment by konqa** [comment]
Hi Tim,
Would this mean the lyric reader is no longer being made? Let me know.

Regards,

*VICTOR BAGU*
*Digital Chef (Web Developer, Graphic Designer)*

**Comment by constsync** [comment]
@konqa I'm thinking that we can pivot to something a bit more relevant that's all, what do you think of that idea? The whole word definition searcher thing.

**Comment by konqa** [comment]
Let's do that. The lyrics one sounded convenient though. 
What will be title of the new project?

**Comment by constsync** [comment]
@konqa It will all be written in the same GitHub repo, we can honestly do both. I've checked out a branch in this repo for the React rewrite. Also there is something else I want to share with you one of my buddies from work gave me a really good suggestion for what we can do with the whole lyrics application idea. PM me on slack and i'll let you know what he said.

**Comment by constsync** [comment]
Here is the gist of what he said i'm thinking we start building it and make it an open source project!  It would be good for singers and songwriters that want to reference the lyrics of a song that they are playing live in a uncluttered UI. It would have a feature where artists can go in and type all of the lyrics for the whatever song they want and give them the ability to save it as well as export the song lyrics as PDF. It would also have the lyric-reader functionality that will play the lyrics out for you while you are reviewing on the bus before a gig. Pretty much this will query db, return lyrics, user can listen read, or both. User can save , both as favorites  and as a downloadable PDF, maybe. Depends on user retention. What do you guys think about this? @konqa @rowanD72
