### ISSUE TITLE
Build UI for Main View 

### ISSUE THREAD

**Issue by constsync** [constsync/lyric-reader#4]
Needs to be built off of Material design guidelines & responsive all the way down to mobile devices.
Also needs to look good on desktop/laptops, the look of the UI can be totally different on desktop/laptop screens, feel free to get creative with this part. 👍  

UI components that this view must have
- Search field
- SongName input field
- ArtistName input field 
- Search button

**Comment by rowanD72** [comment]
This is going to be a fun project to do. Let's get it going!

**Comment by constsync** [comment]
Hack yeah bro, let's get it! 🏃 💥
